import axios from 'axios'
import qs from 'qs'

const axiosInstance = axios.create({
  paramsSerializer: params => {
    return qs.stringify(params, { arrayFormat: 'repeat' })
  },
  baseURL: 'https://api.micadoproject.eu',
  "headers": {
    "Prefer": "resolution=merge-duplicates",
    "apikey": "eyJ4NXQiOiJaalJtWVRNd05USmpPV1U1TW1Jek1qZ3pOREkzWTJJeU1tSXlZMkV6TWpkaFpqVmlNamMwWmc9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImFwcGxpY2F0aW9uIjp7Im93bmVyIjoiYWRtaW4iLCJ0aWVyIjoiVW5saW1pdGVkIiwibmFtZSI6IkRlZmF1bHRBcHBsaWNhdGlvbiIsImlkIjoxLCJ1dWlkIjoiNzBmNGQ5MzEtNmQxYi00ZGJiLThiZGItNjgyNGViZWRhNjA5In0sInRpZXJJbmZvIjp7IlVubGltaXRlZCI6eyJzdG9wT25RdW90YVJlYWNoIjp0cnVlLCJzcGlrZUFycmVzdExpbWl0IjowLCJzcGlrZUFycmVzdFVuaXQiOm51bGx9fSwia2V5dHlwZSI6IlBST0RVQ1RJT04iLCJzdWJzY3JpYmVkQVBJcyI6W3sic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJQb3N0Z1JFU1RBUEkiLCJjb250ZXh0IjoiXC9kYlwvdjAxIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoidjAxIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9XSwiaWF0IjoxNTkwNjUwMDU3LCJqdGkiOiJmZTJlNjdlNi1hZjczLTQzYjItYjVjMS1kNWQxMmIxNjhmZWQifQ==.WKZBZE6aM_R2Ps0_g9eJOt1aKF5zhTMQ4wpD4cO35AX0tZL0-VA8uccZZJW770aouUDCtZs0840E0mykZOpNdFoRO0QeIQkVshmh43QdspPBVjKB7BKfy49LxgZi9SeB-uLxqZwPz9Fxd-d5BY7I8Q1Y7IqyULugeZeSPRt3YUul1dvFzwTJTQ1sD1GphBBdO03YRC4bOyPbtySy55tCBV2LzqTHQ45pUf0boCidIlB7OO5jYkwiIYtjUxASIxRGduUcxJ4ghfhWtUBuEtpIykMh6BZ88TbRKE3_UqZ-veel6sCiOjDgTgW7J3M2l5Az0ivDisEzaf8qtCTQO7u4DA=="
  }
})

export default ({ Vue }) => {
  Vue.prototype.$axios = axiosInstance
}

export { axiosInstance }
