#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg APP_BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             -t $IMAGE_NAME .
